'use client';

import { useState } from 'react';
import { X } from 'lucide-react';

type Lang = 'am' | 'en';
type Modal = 'income' | 'expense' | 'inventory' | 'movement' | 'customer' | 'supplier' | 'crop' | 'activity';
type Item = { id:number; business_id:string; name:string; quantity:number; unit:string };
type Crop = { id:number; name:string };
type Props = { modal:Modal; setModal:(value:Modal|null)=>void; lang:Lang; t:{save:string;cancel:string}; business:string; data:{inventory:Item[];crops:Crop[]}; onSaved:()=>void };

const businessName=(business:string,lang:Lang)=>business==='farm'?(lang==='am'?'እርሻ':'Farm'):(lang==='am'?'የመጠጥ ንግድ':'Beverage');
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}

export function FunctionalRecordModal({modal,setModal,lang,t,business,data,onSaved}:Props){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const body=Object.fromEntries(new FormData(event.currentTarget).entries());body.kind=modal==='income'||modal==='expense'?'transaction':modal==='customer'||modal==='supplier'?'party':modal;if(['income','expense','customer','supplier'].includes(modal))body.type=modal;try{const response=await fetch('/api/data',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const result=await response.json() as {error?:string};if(!response.ok)throw Error(result.error||'Could not save');onSaved();setModal(null)}catch(reason){setError(reason instanceof Error?reason.message:'Could not save')}finally{setBusy(false)}}
 const title=modal==='income'?(lang==='am'?'ገቢ መዝግብ':'Record income'):modal==='expense'?(lang==='am'?'ወጪ መዝግብ':'Record expense'):modal==='inventory'?(lang==='am'?'አዲስ እቃ':'New inventory item'):modal==='customer'?(lang==='am'?'አዲስ ደንበኛ':'New customer'):modal==='supplier'?(lang==='am'?'አዲስ አቅራቢ':'New supplier'):modal==='crop'?(lang==='am'?'አዲስ ሰብል':'New crop'):modal==='activity'?(lang==='am'?'የእርሻ እንቅስቃሴ':'Farm activity'):(lang==='am'?'የእቃ እንቅስቃሴ':'Stock movement');
 return <div className="modal-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target)setModal(null)}}><div className="modal"><div className="modal-head"><div><span>{lang==='am'?'አዲስ መዝገብ':'NEW RECORD'}</span><h2>{title}</h2></div><button type="button" aria-label="Close" onClick={()=>setModal(null)}><X/></button></div><form onSubmit={submit}>
  {modal==='customer'||modal==='supplier'?<><Field label={lang==='am'?'ስም':'Name'}><input name="name" required autoFocus/></Field><div className="form-row"><Field label={lang==='am'?'ስልክ':'Phone'}><input name="phone" type="tel"/></Field><Field label={lang==='am'?'አካባቢ':'Location'}><input name="location"/></Field></div><Field label={lang==='am'?'ንግድ':'Business'}><select name="businessId" defaultValue={business==='all'?(modal==='customer'?'beverage':'farm'):business}><option value="farm">{businessName('farm',lang)}</option><option value="beverage">{businessName('beverage',lang)}</option></select></Field><div className="form-row"><Field label={lang==='am'?'ጠቅላላ መጠን':'Total amount'}><input name="total" type="number" min="0" defaultValue="0"/></Field><Field label={lang==='am'?'የተከፈለ':'Amount paid'}><input name="paid" type="number" min="0" defaultValue="0"/></Field></div><Field label={lang==='am'?'የመክፈያ ቀን':'Due date'}><input name="dueDate" type="date"/></Field><Field label={lang==='am'?'ማስታወሻ':'Notes'}><input name="notes"/></Field></>
  :modal==='crop'?<><div className="form-row"><Field label={lang==='am'?'ሰብል':'Crop'}><input name="name" required autoFocus/></Field><Field label={lang==='am'?'ማሳ / ቦታ':'Field / location'}><input name="field" required/></Field></div><div className="form-row"><Field label={lang==='am'?'የመዝሪያ ቀን':'Planting date'}><input name="plantingDate" type="date" required/></Field><Field label={lang==='am'?'የመከር ቀን':'Expected harvest'}><input name="harvestDate" type="date" required/></Field></div><div className="form-row"><Field label={lang==='am'?'ስፋት (ሄክታር)':'Area (hectares)'}><input name="area" type="number" min="0.01" step="0.01" required/></Field><Field label={lang==='am'?'የተጠበቀ ምርት (kg)':'Expected yield (kg)'}><input name="expectedYield" type="number" min="0" required/></Field></div><Field label={lang==='am'?'ሁኔታ':'Status'}><select name="status"><option value="planned">Planned</option><option value="planted">Planted</option><option value="growing">Growing</option><option value="ready">Ready to harvest</option><option value="harvested">Harvested</option></select></Field></>
  :modal==='activity'?<><Field label={lang==='am'?'እንቅስቃሴ':'Activity'}><select name="activityType"><option value="planting">Planting</option><option value="fertilizing">Fertilizing</option><option value="irrigation">Irrigation</option><option value="spraying">Spraying</option><option value="weeding">Weeding</option><option value="harvesting">Harvesting</option><option value="maintenance">Maintenance</option><option value="labor">Labor</option></select></Field><div className="form-row"><Field label={lang==='am'?'ሰብል':'Crop'}><select name="cropId"><option value="">—</option>{data.crops.map(crop=><option key={crop.id} value={crop.id}>{crop.name}</option>)}</select></Field><Field label={lang==='am'?'ቀን':'Date'}><input name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></Field></div><Field label={lang==='am'?'ወጪ (ብር)':'Cost (ETB)'}><input name="cost" type="number" min="0" defaultValue="0"/></Field><Field label={lang==='am'?'ማስታወሻ':'Notes'}><input name="notes"/></Field></>
  :modal==='movement'?<><Field label={lang==='am'?'እቃ':'Item'}>{data.inventory.length?<select name="itemId" required>{data.inventory.filter(item=>business==='all'||item.business_id===business).map(item=><option key={item.id} value={item.id}>{item.name} ({item.quantity} {item.unit})</option>)}</select>:<div className="inline-empty">{lang==='am'?'መጀመሪያ እቃ ይጨምሩ።':'Add an inventory item first.'}</div>}</Field><div className="form-row"><Field label={lang==='am'?'እንቅስቃሴ':'Movement'}><select name="movementType"><option value="out">{lang==='am'?'ወጪ':'Stock out'}</option><option value="in">{lang==='am'?'ገቢ':'Stock in'}</option></select></Field><Field label={lang==='am'?'ብዛት':'Quantity'}><input name="quantity" type="number" min="0.01" step="0.01" required/></Field></div><Field label={lang==='am'?'ምክንያት':'Reason'}><select name="reason"><option>sold</option><option>used</option><option>damaged</option><option>lost</option><option>adjustment</option></select></Field><input type="hidden" name="date" value={new Date().toISOString().slice(0,10)}/></>
  :modal==='inventory'?<><Field label={lang==='am'?'የእቃ ስም':'Item name'}><input name="name" required autoFocus/></Field><div className="form-row"><Field label={lang==='am'?'ንግድ':'Business'}><select name="businessId" defaultValue={business==='all'?'farm':business}><option value="farm">{businessName('farm',lang)}</option><option value="beverage">{businessName('beverage',lang)}</option></select></Field><Field label={lang==='am'?'ምድብ':'Category'}><input name="category" required/></Field></div><div className="form-row"><Field label={lang==='am'?'ብዛት':'Quantity'}><input name="quantity" type="number" min="0" required/></Field><Field label={lang==='am'?'መለኪያ':'Unit'}><select name="unit"><option>{lang==='am'?'ኪ.ግ':'kg'}</option><option>{lang==='am'?'ሳጥን':'boxes'}</option><option>{lang==='am'?'ሊትር':'liters'}</option><option>{lang==='am'?'ከረጢት':'bags'}</option></select></Field></div><div className="form-row"><Field label={lang==='am'?'የግዢ ዋጋ':'Purchase price'}><input name="purchasePrice" type="number" min="0" required/></Field><Field label={lang==='am'?'ዝቅተኛ ክምችት':'Minimum stock'}><input name="minimumStock" type="number" min="0"/></Field></div><Field label={lang==='am'?'አቅራቢ':'Supplier'}><input name="supplier"/></Field></>
  :<><div className="form-row"><Field label={lang==='am'?'መጠን (ብር)':'Amount (ETB)'}><input name="amount" type="number" min="1" required autoFocus/></Field><Field label={lang==='am'?'ቀን':'Date'}><input name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></Field></div><div className="form-row"><Field label={lang==='am'?'ንግድ':'Business'}><select name="businessId" defaultValue={business==='all'?'farm':business}><option value="farm">{businessName('farm',lang)}</option><option value="beverage">{businessName('beverage',lang)}</option></select></Field><Field label={lang==='am'?'ምድብ':'Category'}><select name="category">{(modal==='income'?['sales','crop-sales','livestock','customer-payment','other']:['purchases','fertilizer','fuel','transport','labor','maintenance','other']).map(category=><option key={category}>{category}</option>)}</select></Field></div><Field label={lang==='am'?'ዝርዝር':'Description'}><input name="description" required/></Field><div className="form-row"><Field label={lang==='am'?(modal==='income'?'ደንበኛ / ምንጭ':'አቅራቢ'):(modal==='income'?'Customer / source':'Supplier')}><input name="party"/></Field><Field label={lang==='am'?'የክፍያ ዘዴ':'Payment method'}><select name="paymentMethod"><option value="cash">{lang==='am'?'ጥሬ ገንዘብ':'Cash'}</option><option value="bank">{lang==='am'?'ባንክ':'Bank'}</option><option value="mobile">{lang==='am'?'ሞባይል ገንዘብ':'Mobile money'}</option></select></Field></div></>}
  {error&&<p className="form-error">{error}</p>}<div className="form-actions"><button type="button" onClick={()=>setModal(null)}>{t.cancel}</button><button className="primary" disabled={busy||(modal==='movement'&&!data.inventory.length)}>{busy?(lang==='am'?'እየተመዘገበ…':'Saving…'):t.save}</button></div>
 </form></div></div>
}
