create table public.businesses (
  id text primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  name_am text not null,
  name_en text not null,
  type text not null check (type in ('farm','beverage'))
);

create table public.transactions (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  business_id text not null references public.businesses(id),
  type text not null check (type in ('income','expense')),
  category text not null,
  amount numeric(14,2) not null check (amount > 0),
  date date not null,
  party text,
  description text not null,
  payment_method text not null default 'cash',
  notes text,
  deleted_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.inventory_items (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  business_id text not null references public.businesses(id),
  name text not null,
  category text not null,
  brand text,
  quantity numeric(14,2) not null check (quantity >= 0),
  unit text not null,
  purchase_price numeric(14,2) not null check (purchase_price >= 0),
  selling_price numeric(14,2),
  minimum_stock numeric(14,2) not null default 0,
  supplier text,
  location text,
  expiration_date date,
  deleted_at timestamptz
);

create table public.inventory_movements (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  item_id bigint not null references public.inventory_items(id),
  business_id text not null references public.businesses(id),
  movement_type text not null check (movement_type in ('in','out','adjustment')),
  reason text not null,
  quantity numeric(14,2) not null check (quantity > 0),
  date date not null,
  notes text,
  created_at timestamptz not null default now()
);

create table public.parties (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  business_id text not null references public.businesses(id),
  type text not null check (type in ('customer','supplier')),
  name text not null,
  phone text,
  location text,
  total numeric(14,2) not null default 0,
  paid numeric(14,2) not null default 0,
  due_date date,
  notes text,
  deleted_at timestamptz
);

create table public.crops (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  business_id text not null references public.businesses(id),
  name text not null,
  field text not null,
  planting_date date not null,
  harvest_date date not null,
  area numeric(10,2) not null,
  expected_yield numeric(14,2) not null,
  actual_yield numeric(14,2) not null default 0,
  status text not null
);

create table public.farm_activities (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  crop_id bigint references public.crops(id),
  type text not null,
  date date not null,
  cost numeric(14,2) not null check (cost >= 0),
  notes text
);

create table public.alerts (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  business_id text references public.businesses(id),
  severity text not null,
  title_am text not null,
  title_en text not null,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create index idx_transactions_owner_business_date on public.transactions(owner_id,business_id,date desc) where deleted_at is null;
create index idx_inventory_owner_business on public.inventory_items(owner_id,business_id) where deleted_at is null;
create index idx_parties_owner_business_type on public.parties(owner_id,business_id,type) where deleted_at is null;
create index idx_movements_owner_item_date on public.inventory_movements(owner_id,item_id,date desc);

do $$
declare owner uuid;
begin
  select id into owner from auth.users where email='birhanukinfu@bereket.local' limit 1;
  if owner is null then raise exception 'Required owner account is missing'; end if;
  insert into public.businesses values ('farm',owner,'እርሻ','Farm','farm'),('beverage',owner,'የመጠጥ ንግድ','Beverage Business','beverage');
  insert into public.transactions (owner_id,business_id,type,category,amount,date,party,description,payment_method) values
    (owner,'beverage','income','sales',126500,'2026-09-09','አበበ ገብረ','የመጠጥ ሽያጭ','bank'),
    (owner,'farm','income','crop-sales',186000,'2026-09-06','ወ/ሮ ሰላም','የበቆሎ ሽያጭ','cash'),
    (owner,'beverage','expense','purchases',118400,'2026-09-07','ሞአ መጠጦች','የመጠጥ ግዢ','bank'),
    (owner,'farm','expense','fertilizer',78500,'2026-09-03','አዲስ አግሮ','ማዳበሪያ ግዢ','cash'),
    (owner,'farm','expense','labor',42900,'2026-09-01','የእርሻ ሰራተኞች','የወር የሰራተኛ ክፍያ','cash'),
    (owner,'beverage','income','sales',173750,'2026-08-25','ብሩክ ሱቅ','የጅምላ ሽያጭ','mobile');
  insert into public.inventory_items (owner_id,business_id,name,category,brand,quantity,unit,purchase_price,selling_price,minimum_stock,supplier,location,expiration_date) values
    (owner,'beverage','ኮካ ኮላ 500ml','beverage','Coca-Cola',8,'ሳጥን',620,760,15,'ሞአ መጠጦች','መጋዘን A','2027-02-15'),
    (owner,'beverage','አምቦ 500ml','beverage','Ambo',34,'ሳጥን',510,650,12,'አምቦ ውሃ','መጋዘን A','2027-04-20'),
    (owner,'farm','NPS ማዳበሪያ','fertilizer',null,12,'ከረጢት',4200,null,20,'አዲስ አግሮ','ዋና መጋዘን',null),
    (owner,'farm','የበቆሎ ዘር','seeds',null,145,'ኪ.ግ',185,null,50,'ኢትዮ ዘር','ዘር መጋዘን','2027-01-10');
  insert into public.parties (owner_id,business_id,type,name,phone,location,total,paid,due_date,notes) values
    (owner,'beverage','customer','አበበ ገብረ','0911 234 567','አዲስ አበባ',68000,43000,'2026-09-05','መደበኛ ደንበኛ'),
    (owner,'beverage','customer','ብሩክ ሱቅ','0912 765 432','ዱከም',47500,27500,'2026-09-18',null),
    (owner,'farm','supplier','አዲስ አግሮ','011 445 6677','አዲስ አበባ',98000,63000,'2026-09-14','የማዳበሪያ አቅራቢ'),
    (owner,'beverage','supplier','ሞአ መጠጦች','011 661 2233','ሰበታ',142000,106000,'2026-09-20',null);
  insert into public.crops (owner_id,business_id,name,field,planting_date,harvest_date,area,expected_yield,actual_yield,status) values
    (owner,'farm','በቆሎ','ምስራቅ ማሳ','2026-05-18','2026-10-20',3.5,6200,0,'growing'),
    (owner,'farm','ጤፍ','ሰሜን ማሳ','2026-07-02','2026-11-12',2,2800,0,'planted');
end $$;

alter table public.businesses enable row level security;
alter table public.transactions enable row level security;
alter table public.inventory_items enable row level security;
alter table public.inventory_movements enable row level security;
alter table public.parties enable row level security;
alter table public.crops enable row level security;
alter table public.farm_activities enable row level security;
alter table public.alerts enable row level security;

revoke all on all tables in schema public from anon, authenticated;
grant select,insert,update on public.businesses,public.transactions,public.inventory_items,public.inventory_movements,public.parties,public.crops,public.farm_activities,public.alerts to authenticated;
grant usage,select on all sequences in schema public to authenticated;

create policy owner_select_businesses on public.businesses for select to authenticated using ((select auth.uid())=owner_id);
create policy owner_select_transactions on public.transactions for select to authenticated using ((select auth.uid())=owner_id);
create policy owner_insert_transactions on public.transactions for insert to authenticated with check ((select auth.uid())=owner_id);
create policy owner_update_transactions on public.transactions for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
create policy owner_select_inventory on public.inventory_items for select to authenticated using ((select auth.uid())=owner_id);
create policy owner_insert_inventory on public.inventory_items for insert to authenticated with check ((select auth.uid())=owner_id);
create policy owner_update_inventory on public.inventory_items for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
create policy owner_select_movements on public.inventory_movements for select to authenticated using ((select auth.uid())=owner_id);
create policy owner_insert_movements on public.inventory_movements for insert to authenticated with check ((select auth.uid())=owner_id);
create policy owner_select_parties on public.parties for select to authenticated using ((select auth.uid())=owner_id);
create policy owner_insert_parties on public.parties for insert to authenticated with check ((select auth.uid())=owner_id);
create policy owner_update_parties on public.parties for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
create policy owner_select_crops on public.crops for select to authenticated using ((select auth.uid())=owner_id);
create policy owner_insert_crops on public.crops for insert to authenticated with check ((select auth.uid())=owner_id);
create policy owner_update_crops on public.crops for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
create policy owner_select_activities on public.farm_activities for select to authenticated using ((select auth.uid())=owner_id);
create policy owner_insert_activities on public.farm_activities for insert to authenticated with check ((select auth.uid())=owner_id);
create policy owner_update_activities on public.farm_activities for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
create policy owner_select_alerts on public.alerts for select to authenticated using ((select auth.uid())=owner_id);
create policy owner_insert_alerts on public.alerts for insert to authenticated with check ((select auth.uid())=owner_id);
create policy owner_update_alerts on public.alerts for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id);
